name: Compila LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Compila LaTeX (con bibliografia)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: false           # Usa pdflatex di default
          latexmk_shell_escape: true            # Necessario per alcuni pacchetti
          extra_system_packages: "biber"        # Installa biber per la bibliografia
          latexmk_args: "-bibtex"               # Abilita gestione bibliografia (bibtex/biber)

      - name: Carica PDF come artifact
        uses: actions/upload-artifact@v4
        with:
          name: appunti-fotonica
          path: main.pdf
