jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: notes
          path: main.pdf
