name: Compila LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile LaTeX
      run: |
        latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: notes
        path: main.pdf
